### ISSUE TITLE
Possible extra system dependency - udunits

### ISSUE THREAD

**Issue by snugghash** [farrellja/URD#10]
Using R-3.4.1, the full install script failed at `ggraph` for me. Further investigation reveals a library `libudunits2.a` is missing.
I installed `udunits` from the AUR, could be under a different name in your distribution.
[Possible extra steps necessary](https://askubuntu.com/a/1057101/)  - 
```
install.packages("udunits2")
devtools::install_github(c("hadley/ggplot2", "GuangchuangYu/ggtree"))
```
`source("https://raw.githubusercontent.com/farrellja/URD/master/URD-Install.R") ` now works.

**Comment by farrellja** [comment]
Were you installing on a linux distribution? libudunits2 is indeed required (annoyingly, due to some of URD's dependencies). It seems to be part of Mac OS X and Windows, but often requires manual installation on Linux. I added a section to "Troubleshooting" in install.md, but want to double-check that this does not affect any other OS.

**Comment by snugghash** [comment]
I tested this and ggraph required libudunits2 on Arch, Debian, CentOS.
I did not test this personally on Windows, but I believe you're right - I do not recall witnessing the issue when the install happened.

Sorry for the late reply.

**Comment by snugghash** [comment]
Alright, I can confirm that windows R3.4.1 doens't require additional system dependencies.
Thanks for adding this to the documentation!
