### ISSUE TITLE
Can't install URD due to TTR error on mac

### ISSUE THREAD

**Issue by tsotnech** [farrellja/URD#16]
Hi Guys, 

I wanted to try URD on my scRNA-seq data. I tried installing it from CRAN or GitHub but I'm always getting an issue that TTR package can't be installed that is an issue to install destiny package and finally URD installation isn't successful. 

```
> make: gfortran: No such file or directory
> make: *** [movingAverages.o] Error 1
> ERROR: compilation failed for package ‘TTR’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/TTR’
> Warning in install.packages :
>   installation of package ‘TTR’ had non-zero exit status
```

I tried to install Fortran compiler on mac but it doesn't help with TTR. Currently I'm running R 3.5.1. any help would be appreciated. 
Worst case scenario I could downgrade my R version, but not sure which version will be supported by all the packages. 

Cheers!

**Comment by farrellja** [comment]
Hi tsotnech,

I haven't encountered this problem myself. But, I can think of a few things you might try:

First, you could see whether you can install the package directly as a binary. Try either ```install.packages("TTR", type="binary")``` and see whether it works. Or alternatively, download the binary from the CRAN page directly and using ```install.packages("path\to\package", repos=NULL)``` and see whether that works.

Alternatively, it looks like you're installing on Mac OS X. Do you have the command line developer tools installed? If not, you might try installing them by typing ```xcode-select --install``` from the command line. I believe they are required for the correct compilation of many packages, so that might help?

If not, currently, I am using R 3.4.1, destiny_2.6.2, TTR_0.23-2, and Mac OS 10.12.6 so those versions all  work together.

Hope that helps; Best, Jeff

**Comment by tsotnech** [comment]
Hi Jeff,

Thanks a lot for the suggestions, I have Xcode and I read on TTF GitHub that it might need Fortran compiler on mac, so I installed it as well but didn't help.

However installing the binary package helped. when I was trying to install destiny, it asked me to update TTR and when I updated all, it gave exactly same error. So installing the binary and not updating the TTR was a solution. I could successfully install URD afterwards. 

thanks again for your help,

Best,
Tsotne
