### ISSUE TITLE
object@group instead of object@group.ids? 

### ISSUE THREAD

**Issue by Kgies10** [farrellja/URD#4]
Hi there, 

I'm trying to do gene cascade in a 2D URD tree, but when I call  aucprTestAlongTree as in: 

  ```
markers <- aucprTestAlongTree(objTree, pseudotime="pseudotime", tips=tip,
              log.effect.size=0.4, auc.factor = 1.25, max.auc.threshold = 0.85, 
              frac.must.express = 0.1, frac.min.diff = 0, genes.use=genes.use, 
              only.return.global=F, must.beat.sibs=0.6, report.debug=T)
```

I get this error: 

```
Error in markersAUCPR(object = object, cells.1 = cells.1, cells.2 = cells.2,  : 
  no slot of name "group" for this object of class "URD"
```

So I looked at markersAUCPR and it calls: 

    if (is.null(clustering)) {
        clust.use <- object@group 

But I didn't think URD objects had a slot called "group" just "group.ids".  Why does markersAUCPR 
 reference object@group? 

For reference my tree, objTree, is an URD object: 18385 genes x 23602 cells.  Any help would be greatly appreciated!   Many thanks!

**Comment by YiqunW** [comment]
Hi Jeff,

I hope you are enjoying HongKong!

I tried to look into this issue since you are on your vacation. When I tried to create an URD object following our supplemental analysis, the created object already has an empty slot @group. However, then I updated URD package to the current version, and when I repeated the same URD object creation process, there is no longer an @group slot in the newly created object. I loaded in some URD object in our walk-through folder, and they all have @group slot before I updated the package, but didn’t have that slot anymore after the update.

I also searched through our supplemental analysis and all the URD functions on git, and didn’t find any function or step that creates an @group slot.

Before I spend more time looking into it, I wonder if you know what the problem is. If you give me a little bit instructions, I can try to fix it. But don’t work on it if it’s complicated to figure out! 

Yiqun

**Comment by farrellja** [comment]
Just before releasing the software, I removed some deprecated slots from the URD object, which included @group. I thought I had removed all references to it, but clearly missed a couple. I just fixed the bug, and increased the version number to 1.0.1. So, go ahead and update your URD installation (```devtools::install_github(repo="farrellja/URD")```) and it should be corrected.

**Comment by Kgies10** [comment]
Great, thanks for updating!
