### ISSUE TITLE
Cell types annotation for the Zebrafish datasets

### ISSUE THREAD

**Issue by yancychy** [farrellja/URD#46]
Hi,
      I checked  https://portals.broadinstitute.org/single_cell/study/SCP162/single-cell-reconstruction-of-developmental-trajectories-during-zebrafish-embryogenesis#study-summary. 
    I find the zebrafish lineages build by URD is very nice. The tips shows a clear cell differentiation trajectories.  But I cannot find the cell types annotations for the clusters.  Can I use the markers genes used in your analysis to annotate all clusters (no only tips)?  Thanks

**Comment by MichaelPeibo** [comment]
Hi @yancychy 
Check the supplementary analysis here, the author has release the full code to repeat it.
https://github.com/farrellja/URD/blob/master/Analyses/SupplementaryAnalysis/URD-03-ClusteringAndDeterminingTips.Rmd
Good luck!

**Comment by yancychy** [comment]
Thanks Peibo. It is only for the cell types annotation at the final time stage (tips cells). I mean the cell annotation at the other time stages.  I will try it using these markers to annotate the cells at other time stages.

**Comment by farrellja** [comment]
@yancychy We didn't annotate clusters from each stage, instead relying on their assignments in the trajectories. I'm happy to share my annotation table for the final (6-somite) stage, if needed or it would be helpful. We didn't put a ton of work into selecting the perfect clustering (i.e. resolution or number of nearest neighbors) from each stage (again, because we were using the trajectories to manage cell type assignment), so you may want to generate your own clusterings of those stages. The marker genes we used will help to annotate many of the clusters; you could also look at the gene expression cascades in the supplement to find markers that might be more appropriate for earlier stages in many cases. You can always check how specific they are on the trajectory tree. Additionally, ZFIN is a great resource for marker genes if you need. Lastly, if you are generating clusters to perform differential expression testing, you could download the URD object and use the annotated lineages as input into differential expression testing as well. Hope that helps.

**Comment by yancychy** [comment]
Hi Farrellja, 
      Thanks very much. I have downloaded the URD object. I will try it to annotate the clusters with your markers and ZFIN.
