### ISSUE TITLE
calcDM warning

### ISSUE THREAD

**Issue by AndyR2** [farrellja/URD#61]
I am working with a converted Seurat v3 obj (used the seuratToURD2 function) resulting in:
[URD object: 21019 genes x 20000 cells].

To create the diffusion map I used the following
`xxx <- calcDM(xxx, knn=141, sigma.use=NULL)`
  #[1] "destiny determined an optimal global sigma of 38"

This ran several hours before finishing , and giving the following warning:
  _#Warning message:
  #In DiffusionMap(data.use, sigma = sigma.use, k = knn, n_eigs = dcs.store,  :
  #You have 21019 genes. Consider passing e.g. n_pcs = 50 to speed up computation._

I'd like to implement the suggestion, but I don't understand 'passing n_pcs = 50'.   How would I script that for the calcDM function?  'n_pcs' is not a variable that I can find.

I am also wondering if URD can map onto a UMAP projection, or is tSNE the only dim. red.  that can be used.  thx

**Comment by farrellja** [comment]
Hi @AndyR2 

`calcDM` calls the _destiny_ package behind the scenes, and this seems to be a chance in the functionality of their package. Right now it doesn't support passing arbitrary parameters through to destiny, but I can add that. However, the issue here is that for a typical workflow, we would use calculate the diffusion map directly on gene expression, but on a selection of highly variable genes (1,000-3,000 genes), whereas you are calculating on (seemingly) all genes. This is controlled using the `genes.use` parameter, which defaults to the calculated variable genes.

Re: UMAP. We don't have a specific slot for UMAP projections, right now, but I can share a function with you that calculate one and put it in the tSNE slot. This should make it into a future release, anyway. Can you share your email?

Jeff
